### ISSUE TITLE
Unraid Docker ClamAV: Could not download icon

### ISSUE THREAD

**Issue by Alkali-V2** [tquizzle/Docker-xml#12]
Hello! I noticed in my logs that I hit an error message about a missing ClamAV icon and I think I found your repo related to it.  Just wanted to see if we could get the icon added back for Unraid ClamAV? 

`Jul 14 17:55:15 Tower root: ClamAV: Could not download icon https://raw.githubusercontent.com/tquizzle/Docker-xml/master/img/clamav.png`

 I'm attaching the Wikimedia Commons logo they posted if you can use that.  I'm not sure if you can but wanted to save you a search just in case it can be used.
![ClamAV_Logo](https://github.com/user-attachments/assets/a0b2809b-3f2e-4f6e-8f4a-e21d3174deb4)

Thanks!

**Comment by tquizzle** [comment]
Thanks for that! Updated
